### ISSUE TITLE
Problem implementing pdf_viewer in st.tabs

### ISSUE THREAD

**Issue by OliverPSZ** [lfoppiano/streamlit-pdf-viewer#53] opened 2024-06-18 07:13 UTC
I'm quite new in Streamlit and as stated in the title I have been facing problems trying to implement the pdf viewer in my project. My solution has a set of st.tabs and I need to display a different pdf on each one of them but for now when I run my code it only renders the one from the tab that is open when the app is refreshed, when I switch tabs the rest remain blank. 

When I use an st.markdown with an iframe (<iframe src="data:application/pdf;base64,{base64_pdf}#zoom=FitV" width="90%" height="700" type="application/pdf"></iframe>) it works but only on Firefox but not on Chrome or Edge.

**Comment by lfoppiano** [comment] 2024-06-22 21:10
Hi @OliverPSZ, could you please share a working example?

**Comment by moscaAle29** [comment] 2024-07-02 13:35
Hi @lfoppiano , having a similar issue here
I have a set of references in one tab and, based on the selected reference, a second tab should display the associated pdf and page.
the code goes something like this
`ref, docs = st.tabs(["References","Docs"])
with ref:
    #logic to select a reference
with docs:
    page=st.session_state.page
    pdf_viewer(st.session_state.document,
                       pages_to_render=[page-1,page,page+1],
                       width=1000)
`
As of now this doesn't work
**BUT**
If I modify something in the code and click "rerun" while being in the correct tab it works as expected
is there a workaround ?

**Comment by lfoppiano** [comment] 2024-07-11 01:28
I think the issue is that the document is not attached to the children of the correct tab. One workaround, I think, would be to have the "doc" tab selected when you call the `pdf_viewer()`, so that the viewer is correct when rendered. An alternative would be to display the references on 1) a different columns instead of tabs, or, 2) in the sidebar. 
I'm not sure how much users like to click back and forth on the tabs when they have to inspect multiple references. But this is just my humble opinion. 😅 

The problem comes on a problem I have encountered a few times already, which is on how to calculate correctly the height of the pages, when the tab of the pdf is not visible everything gets to 0 and the pages are not shown.

**Comment by lfoppiano** [comment] 2024-08-01 19:31
I'm closing this as it's a duplicate of #56

**Closed** 2024-08-06 09:10 UTC
Labels: bug, help wanted, implemented
