### ISSUE TITLE
PDF is not shown when I set the rendering to 'legacy_iframe' or 'legacy_embed'. I want a scrollable and zoomable PDF within a frame.

### ISSUE THREAD

**Issue by mingjun1120** [lfoppiano/streamlit-pdf-viewer#40] opened 2024-03-01 04:23 UTC
I want to create a page with 2 columns (`st.columns([2, 1]`) where the left column will display the PDF uploaded by users and the right column will allow users to ask questions **(RetrievalQA, not Conversational type)** related to the uploaded file. However, I have found that some of the files are not displayed on the web when I set the **rendering** parameter to `legacy_iframe` or `legacy_embed`. The `unwrap` parameter works fine; the PDF file can be displayed, but I have to scroll to the bottom of the entire page to see the file contents if the file has many pages.

### Below is my code:
```
import base64
import streamlit as st
from streamlit_javascript import st_javascript
from streamlit_pdf_viewer import pdf_viewer

st.set_page_config(page_title="pdf-GPT", page_icon="📖", layout="wide")
st.write("<h2 style='text-align: center;'><span style='color: blue;'>TEST</span> Legal </h2>", unsafe_allow_html=True)

with st.sidebar:

    uploaded_file = st.file_uploader(
        "Upload file", type=["pdf"], 
        help="Only PDF files are supported", 
    )

col1, col2 = st.columns(spec=[2, 1])

if uploaded_file:
    with col1:
        ui_width = st_javascript("window.innerWidth")
        
        # Read file as bytes:
        bytes_data = uploaded_file.getvalue()
        
        # Embed PDF in HTML
        pdf_display = pdf_viewer(input=bytes_data, rendering='unwrap')
        
        # Display file
        st.markdown(pdf_display, unsafe_allow_html=True)
    
    with col2:
        question = st.text_input(
            "Ask something about the article",
            placeholder="Can you give me a short summary?",
            disabled = not uploaded_file,
        )
```

### How the web looks like:
![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/54136320/2e098ac7-5633-4bb3-b909-4c3b07372f96)

### Sample file:
[2024 EY Open Science Data Challenge Participant Guidance.pdf](https://github.com/lfoppiano/streamlit-pdf-viewer/files/14456414/2024.EY.Open.Science.Data.Challenge.Participant.Guidance.pdf)

**Comment by lfoppiano** [comment] 2024-03-01 05:37
@mingjun1120 thanks you. 

I confirmed that your PDF works fine with the `rendering` set to 'legacy_iframe' or 'legacy_embed'. You can use lfoppiano-document-qa.hf.space/ and select "Native rendering browser". 

Then, checking your code I think that this: 
```python 
        # Embed PDF in HTML
        pdf_display = pdf_viewer(input=bytes_data, rendering='unwrap')
        
        # Display file
        st.markdown(pdf_display, unsafe_allow_html=True)
```

you should rewrite it as: 

```
pdf_viewer(input=bytes_data, rendering='unwrap')
``` 

or 

```
pdf_viewer(input=bytes_data, rendering='legacy_iframe')
```

**Comment by mingjun1120** [comment] 2024-03-01 05:47
@lfoppiano No, it does not work. Even I replace to `pdf_viewer(input=bytes_data, rendering='legacy_iframe')`.

Below is my updated code:
```
import base64
import streamlit as st
from streamlit_javascript import st_javascript
from streamlit_pdf_viewer import pdf_viewer

st.set_page_config(page_title="pdf-GPT", page_icon="📖", layout="wide")
st.write("<h2 style='text-align: center;'><span style='color: blue;'>TEST</span> Legal </h2>", unsafe_allow_html=True)

with st.sidebar:

    uploaded_file = st.file_uploader(
        "Upload file", type=["pdf"], 
        help="Only PDF files are supported", 
    )

col1, col2 = st.columns(spec=[2, 1])

if uploaded_file:
    with col1:
        ui_width = st_javascript("window.innerWidth")
        
        # Read file as bytes:
        bytes_data = uploaded_file.getvalue()
        
        # Embed PDF in HTML
        pdf_display = pdf_viewer(input=bytes_data, rendering='legacy_iframe')
        
        # Display file
        st.markdown(pdf_display, unsafe_allow_html=True)
    
    with col2:
        question = st.text_input(
            "Ask something about the article",
            placeholder="Can you give me a short summary?",
            disabled = not uploaded_file,
        )
```

**Comment by mingjun1120** [comment] 2024-03-01 06:03
I tried your app with the sample PDF file I sent earlier, the PDF was not shown also.

**Screenshot:**
![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/54136320/5a198bb1-ec32-4e96-aa3e-09eca7f50af5)

**Comment by lfoppiano** [comment] 2024-03-01 06:06
Ah, sorry about that.

If you set the height to anything, you should be able to see the PDF. This is probably due to #35 , but I did not expect this to be happening also on the legacy rendering. 

As an alternative, could you use streamlit-pdf-viewer version 0.0.7 and keep your code (without setting the height) and let me know if that works?

**Comment by lfoppiano** [comment] 2024-03-01 06:08
> I tried your app with the sample PDF file I sent earlier, the PDF was not shown also.
> [...]

Oh this is weird... cause ... it worked for me: 

![image](https://github.com/lfoppiano/streamlit-pdf-viewer/assets/15426/bdeb8a44-7ddc-4fd4-afd7-3a78bae685c2)

**Comment by mingjun1120** [comment] 2024-03-01 06:19
> Ah, sorry about that.
> 
> If you set the height to anything, you should be able to see the PDF. This is probably due to #35 , but I did not expect this to be happening also on the legacy rendering.
> 
> See:
> 
> ![image](https://private-user-images.githubusercontent.com/15426/309164160-2c856c66-054c-4d34-9434-e605933cedcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzM4NjIsIm5iZiI6MTcwOTI3MzU2MiwicGF0aCI6Ii8xNTQyNi8zMDkxNjQxNjAtMmM4NTZjNjYtMDU0Yy00ZDM0LTk0MzQtZTYwNTkzM2NlZGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA2MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYWUwOWI2ZWY1MGE5NGEzNmE2NTBlZTU4ZmIyNmFhYmFjMWNkMWY5MGE1ZGIyMmY5ZDE5ODA4NzI2YmY4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dpixOq6PiEa1dmrQTsWC1DkWnXidRCpaFhM8jv03quk)
> 
> As an alternative, could you try streamlit-pdf-viewer version 0.0.7 with your initial code (without setting the height) and let me know if that works?

Hmm, I tried the `0.0.7` version, but the same error still exists. It's weird.

**Comment by lfoppiano** [comment] 2024-03-01 06:55
> Hmm, I tried the `0.0.7` version, but the same error still exists and I did not set any height either. It's weird! The code I used is the same as the code I sent previously, the only thing that was changed was the `streamlit-pdf-viewer` version.

yeah, it's weird, I've been spending quite a substantial amount of time in the last weeks figuring out some weird behaviours. 
Anyway, if you set the height, does it work? I know it's not a solution, but at least you are not stuck, meanwhile, we fix this bug. 😅

**Comment by mingjun1120** [comment] 2024-03-01 07:10
I tried, still fail! 😥

**Updated code:**
```
import base64
import streamlit as st
from streamlit_javascript import st_javascript
from streamlit_pdf_viewer import pdf_viewer

st.set_page_config(page_title="pdf-GPT", page_icon="📖", layout="wide")
st.write("<h2 style='text-align: center;'><span style='color: blue;'>TEST</span> Legal </h2>", unsafe_allow_html=True)

with st.sidebar:

    uploaded_file = st.file_uploader(
        "Upload file", type=["pdf"], 
        help="Only PDF files are supported", 
    )

col1, col2 = st.columns(spec=[2, 1])

if uploaded_file:
    with col1:
        
        ui_width = st_javascript("window.innerWidth") + 20
        
        # Read file as bytes:
        bytes_data = uploaded_file.getvalue()
        
        # Embed PDF in HTML
        pdf_display = pdf_viewer(input=bytes_data, rendering='legacy_iframe', height=700)
        
        # Display file
        st.markdown(pdf_display, unsafe_allow_html=True)
    
    with col2:
        question = st.text_input(
            "Ask something about the article",
            placeholder="Can you give me a short summary?",
            disabled = not uploaded_file,
        )
```

**Comment by lfoppiano** [comment] 2024-03-01 07:16
I tested your code with both 0.0.7 and 0.0.8, copied 1:1 and it works for me as long as I set the height. 
I'm running out of ideas, I'm afraid 😭 

Maybe try to refresh your browser with ctrl+shift+r.

**Comment by mingjun1120** [comment] 2024-03-01 09:33
I tested the same code on my other laptop and my friend's laptop, and they all experienced the same issue.

**Comment by lfoppiano** [comment] 2024-03-02 08:30
Noted. We will try to solve this shortly.

**Comment by lfoppiano** [comment] 2024-03-03 23:30
@mingjun1120 Could you please let me know in which browser did you test it?

**Comment by mingjun1120** [comment] 2024-03-04 10:20
> @mingjun1120 Could you please let me know in which browser did you test it?
> 
> If you use Chrome/Chromium/Brave, the iframe/embed PDF loading is not running from within the iframe of the component. I did not know there were such limitations when we first implemented the feature.
> 
> You should use the classical approach discussed in many places including https://discuss.streamlit.io/t/display-pdf-in-streamlit/62274
> 
> Does this help?

Hi, I tested on both **Chrome** and **Edge** last time. Both also didn't work out.

**Comment by lfoppiano** [comment] 2024-03-04 21:44
Yes, so Edge is not supported at the moment, but Chrome should be. 
I wonder if you could try it with Firefox.

**Comment by lfoppiano** [comment] 2024-03-26 13:31
After investigating for a few weeks, we will deprecate the legacy methods, as there is no solution or workaround. If update to version 0.0.9 and specify the height you might have a smaller window, and the scrolling might be not necessary.

**Comment by lfoppiano** [comment] 2024-04-03 21:21
FYI I'm considering deprecating the legacy methods because they cause too much trouble. 

This issue has already been reported on streamlit app https://github.com/streamlit/streamlit/issues/1088#issuecomment-979400828 and https://github.com/streamlit/streamlit/issues/1088#issuecomment-829469172

**Comment by lfoppiano** [comment] 2024-05-11 22:53
The fact that the legacy* methods do not work on Chrome and C is now documented. I think we can close this. @mingjun1120 feel free to reopen if you need anything else.

**Closed by lfoppiano** 2024-05-11 22:53 UTC
Labels: bug, frontend, priority:high, browser:edge, browser:chrom*
